MAX_DISPLAY_LEN = 64
PGIE_CLASS_ID_FIRE = 0
PGIE_CLASS_ID_OTHER = 1
PGIE_CLASS_ID_SMOKE = 2
MUXER_OUTPUT_WIDTH = 1920
MUXER_OUTPUT_HEIGHT = 1080
MUXER_BATCH_TIMEOUT_USEC = 33000
TILED_OUTPUT_WIDTH = 1280
TILED_OUTPUT_HEIGHT = 720
GST_CAPS_FEATURES_NVMM = "memory:NVMM"
OSD_PROCESS_MODE = 0
OSD_DISPLAY_TEXT = 0
PGIE_CLASSES = ["Fire", "Other", "Smoke"]

udp_port = 5400
rtsp_port = 8557